### ISSUE TITLE
Error in Image Reading

### ISSUE THREAD

**Issue by ymzhang1919** [DrSleep/tensorflow-deeplab-lfov#4]
In function read_images_from_disk( )
           h_new = tf.to_int32(tf.mul(tf.to_float(tf.shape(img)[1]), scale))
           w_new = tf.to_int32(tf.mul(tf.to_float(tf.shape(img)[1]), scale))

h_new and w_new have the same value

**Comment by DrSleep** [comment]
Nice catch!
Fixed.
