### ISSUE TITLE
model will diverge after 10000 iterations

### ISSUE THREAD

**Issue by gaopeng-eugene** [DrSleep/tensorflow-deeplab-lfov#5]
I use your default parameters for training

python train.py --restore_from ./model.ckpt.pretrained

however, the model will diverage after 11000 iterations

**Comment by gaopeng-eugene** [comment]
step 12839 	 loss = 0.403, (1.025 sec/step)
step 12840 	 loss = 0.395, (1.026 sec/step)
step 12841 	 loss = 0.529, (1.012 sec/step)
step 12842 	 loss = 0.325, (1.024 sec/step)
step 12843 	 loss = 0.498, (1.001 sec/step)
step 12844 	 loss = 0.382, (1.003 sec/step)
step 12845 	 loss = 0.741, (1.012 sec/step)
step 12846 	 loss = 0.946, (1.017 sec/step)
step 12847 	 loss = 0.744, (1.008 sec/step)
step 12848 	 loss = 1.782, (1.044 sec/step)
step 12849 	 loss = 1.319, (1.035 sec/step)
step 12850 	 loss = 0.858, (1.007 sec/step)
step 12851 	 loss = 0.690, (1.060 sec/step)
step 12852 	 loss = 0.658, (1.020 sec/step)
step 12853 	 loss = 1.145, (1.037 sec/step)
step 12854 	 loss = 1.047, (1.035 sec/step)
step 12855 	 loss = 0.413, (0.992 sec/step)
step 12856 	 loss = 0.562, (1.010 sec/step)
step 12857 	 loss = 0.425, (1.291 sec/step)
step 12858 	 loss = 0.496, (1.017 sec/step)
step 12859 	 loss = 0.607, (1.011 sec/step)
step 12860 	 loss = 0.715, (1.016 sec/step)
step 12861 	 loss = 0.571, (1.031 sec/step)
step 12862 	 loss = 0.657, (1.020 sec/step)
step 12863 	 loss = 0.742, (0.990 sec/step)
step 12864 	 loss = 0.480, (1.009 sec/step)
step 12865 	 loss = 0.524, (1.015 sec/step)
step 12866 	 loss = 0.770, (1.007 sec/step)
step 12867 	 loss = 0.623, (1.012 sec/step)
step 12868 	 loss = 0.549, (1.036 sec/step)
step 12869 	 loss = 0.414, (1.027 sec/step)
step 12870 	 loss = 0.576, (1.006 sec/step)
step 12871 	 loss = 0.636, (0.996 sec/step)
step 12872 	 loss = 0.417, (0.997 sec/step)
step 12873 	 loss = 0.300, (1.004 sec/step)
step 12874 	 loss = 0.341, (1.028 sec/step)
step 12875 	 loss = 0.514, (1.007 sec/step)
step 12876 	 loss = 0.420, (1.032 sec/step)
step 12877 	 loss = 0.673, (1.017 sec/step)
step 12878 	 loss = 0.424, (1.029 sec/step)
step 12879 	 loss = 0.333, (1.009 sec/step)
step 12880 	 loss = 0.394, (1.016 sec/step)
step 12881 	 loss = 0.503, (0.983 sec/step)
step 12882 	 loss = 0.378, (0.973 sec/step)
step 12883 	 loss = 0.479, (0.991 sec/step)
step 12884 	 loss = 0.336, (1.011 sec/step)
step 12885 	 loss = 0.418, (1.000 sec/step)
step 12886 	 loss = 0.312, (1.026 sec/step)
step 12887 	 loss = 0.361, (1.013 sec/step)
step 12888 	 loss = 0.432, (1.038 sec/step)
step 12889 	 loss = 0.290, (1.007 sec/step)
step 12890 	 loss = 0.446, (1.007 sec/step)
step 12891 	 loss = 0.366, (1.026 sec/step)
step 12892 	 loss = 0.525, (0.974 sec/step)
step 12893 	 loss = 0.496, (1.028 sec/step)
step 12894 	 loss = 0.528, (1.018 sec/step)
step 12895 	 loss = 0.745, (1.044 sec/step)
step 12896 	 loss = 0.523, (1.056 sec/step)
step 12897 	 loss = 0.772, (1.019 sec/step)
step 12898 	 loss = 0.738, (1.026 sec/step)
step 12899 	 loss = 0.540, (1.041 sec/step)
step 12900 	 loss = 0.415, (1.020 sec/step)
step 12901 	 loss = 0.594, (1.000 sec/step)
step 12902 	 loss = 0.668, (1.075 sec/step)
step 12903 	 loss = 0.607, (1.001 sec/step)
step 12904 	 loss = 0.510, (1.013 sec/step)
step 12905 	 loss = 0.459, (1.021 sec/step)
step 12906 	 loss = 0.635, (0.997 sec/step)
step 12907 	 loss = 0.766, (1.029 sec/step)
step 12908 	 loss = 0.542, (1.020 sec/step)
step 12909 	 loss = 0.515, (1.005 sec/step)
step 12910 	 loss = 0.435, (1.018 sec/step)
step 12911 	 loss = 0.748, (1.029 sec/step)
step 12912 	 loss = 0.674, (1.029 sec/step)
step 12913 	 loss = 0.597, (1.008 sec/step)
step 12914 	 loss = 0.469, (1.026 sec/step)
step 12915 	 loss = 0.437, (1.016 sec/step)
step 12916 	 loss = 0.560, (0.995 sec/step)
step 12917 	 loss = 0.600, (1.028 sec/step)
step 12918 	 loss = 0.386, (0.974 sec/step)
step 12919 	 loss = 0.701, (1.036 sec/step)
step 12920 	 loss = 0.265, (1.009 sec/step)
step 12921 	 loss = 0.332, (0.995 sec/step)
step 12922 	 loss = 0.493, (1.028 sec/step)
step 12923 	 loss = 0.851, (1.006 sec/step)
step 12924 	 loss = 0.653, (1.017 sec/step)
step 12925 	 loss = 0.641, (1.045 sec/step)
step 12926 	 loss = 0.472, (1.033 sec/step)
step 12927 	 loss = 0.290, (0.996 sec/step)
step 12928 	 loss = 0.371, (1.009 sec/step)
step 12929 	 loss = 0.497, (1.020 sec/step)
step 12930 	 loss = 0.501, (0.999 sec/step)
step 12931 	 loss = 0.514, (1.034 sec/step)
step 12932 	 loss = 0.374, (0.973 sec/step)
step 12933 	 loss = 0.765, (1.023 sec/step)
step 12934 	 loss = 1.315, (1.015 sec/step)
step 12935 	 loss = 0.610, (1.027 sec/step)
step 12936 	 loss = 0.583, (0.992 sec/step)
step 12937 	 loss = 0.803, (0.997 sec/step)
step 12938 	 loss = 1.202, (1.009 sec/step)
step 12939 	 loss = 0.447, (1.045 sec/step)
step 12940 	 loss = 0.602, (1.023 sec/step)
step 12941 	 loss = 0.468, (1.012 sec/step)
step 12942 	 loss = 1.010, (1.031 sec/step)
step 12943 	 loss = 0.687, (1.000 sec/step)
step 12944 	 loss = 0.595, (1.007 sec/step)
step 12945 	 loss = 0.487, (1.026 sec/step)
step 12946 	 loss = 0.682, (1.005 sec/step)
step 12947 	 loss = 0.502, (1.040 sec/step)
step 12948 	 loss = 0.748, (1.033 sec/step)
step 12949 	 loss = 1.150, (1.037 sec/step)
step 12950 	 loss = 0.897, (0.998 sec/step)
step 12951 	 loss = 0.653, (1.031 sec/step)
step 12952 	 loss = 0.769, (1.033 sec/step)
step 12953 	 loss = 0.927, (1.035 sec/step)
step 12954 	 loss = 1.602, (1.033 sec/step)
step 12955 	 loss = 0.662, (1.051 sec/step)
step 12956 	 loss = 0.403, (1.027 sec/step)
step 12957 	 loss = 0.560, (1.019 sec/step)
step 12958 	 loss = 0.661, (1.048 sec/step)
step 12959 	 loss = 0.732, (1.007 sec/step)
step 12960 	 loss = 0.501, (1.007 sec/step)
step 12961 	 loss = 0.500, (0.994 sec/step)
step 12962 	 loss = 0.449, (0.987 sec/step)
step 12963 	 loss = 0.508, (1.000 sec/step)
step 12964 	 loss = 0.701, (1.061 sec/step)
step 12965 	 loss = 0.635, (1.008 sec/step)
step 12966 	 loss = 0.690, (1.019 sec/step)
step 12967 	 loss = 0.773, (1.020 sec/step)
step 12968 	 loss = 0.504, (1.000 sec/step)
step 12969 	 loss = 0.525, (1.020 sec/step)
step 12970 	 loss = 0.413, (1.025 sec/step)
step 12971 	 loss = 0.600, (1.000 sec/step)
step 12972 	 loss = 0.428, (1.019 sec/step)
step 12973 	 loss = 0.737, (1.016 sec/step)
step 12974 	 loss = 0.711, (1.000 sec/step)
step 12975 	 loss = 0.413, (1.035 sec/step)
step 12976 	 loss = 0.426, (1.000 sec/step)
step 12977 	 loss = 0.469, (0.999 sec/step)
step 12978 	 loss = 0.592, (0.996 sec/step)
step 12979 	 loss = 0.818, (1.010 sec/step)
step 12980 	 loss = 0.890, (1.032 sec/step)
step 12981 	 loss = 1.108, (1.015 sec/step)
step 12982 	 loss = 1.679, (1.002 sec/step)
step 12983 	 loss = 1.788, (0.988 sec/step)
step 12984 	 loss = 1.253, (0.997 sec/step)
step 12985 	 loss = 1.817, (1.028 sec/step)
step 12986 	 loss = 0.940, (0.989 sec/step)
step 12987 	 loss = 1.235, (0.995 sec/step)
step 12988 	 loss = 1.302, (1.011 sec/step)
step 12989 	 loss = 0.942, (1.017 sec/step)
step 12990 	 loss = 0.532, (1.021 sec/step)
step 12991 	 loss = 0.677, (0.999 sec/step)
step 12992 	 loss = 1.077, (1.036 sec/step)
step 12993 	 loss = 0.642, (0.981 sec/step)
step 12994 	 loss = 1.034, (1.002 sec/step)
step 12995 	 loss = 0.751, (1.008 sec/step)
step 12996 	 loss = 0.737, (1.031 sec/step)
step 12997 	 loss = 0.602, (1.026 sec/step)
step 12998 	 loss = 1.115, (1.000 sec/step)
step 12999 	 loss = 0.915, (1.017 sec/step)
The checkpoint has been created.
step 13000 	 loss = 5.128, (5.495 sec/step)
step 13001 	 loss = 0.860, (0.743 sec/step)
step 13002 	 loss = 0.769, (0.724 sec/step)
step 13003 	 loss = 0.760, (0.985 sec/step)
step 13004 	 loss = 0.980, (1.017 sec/step)
step 13005 	 loss = 0.696, (1.007 sec/step)
step 13006 	 loss = 1.241, (1.040 sec/step)
step 13007 	 loss = 0.916, (1.009 sec/step)
step 13008 	 loss = 2.026, (1.014 sec/step)
step 13009 	 loss = 1.065, (1.013 sec/step)
step 13010 	 loss = 1.597, (1.019 sec/step)
step 13011 	 loss = 1.068, (1.027 sec/step)
step 13012 	 loss = 1.313, (1.073 sec/step)
step 13013 	 loss = 1.231, (0.975 sec/step)
step 13014 	 loss = 1.242, (1.014 sec/step)
step 13015 	 loss = 0.881, (0.994 sec/step)
step 13016 	 loss = 1.231, (1.008 sec/step)
step 13017 	 loss = 1.679, (1.043 sec/step)
step 13018 	 loss = 1.370, (1.037 sec/step)
step 13019 	 loss = 0.733, (1.020 sec/step)
step 13020 	 loss = 1.097, (1.010 sec/step)
step 13021 	 loss = 1.006, (1.014 sec/step)
step 13022 	 loss = 1.876, (0.995 sec/step)
step 13023 	 loss = 0.825, (1.042 sec/step)
step 13024 	 loss = 0.649, (1.015 sec/step)
step 13025 	 loss = 1.098, (1.030 sec/step)
step 13026 	 loss = 0.931, (0.982 sec/step)
step 13027 	 loss = 1.544, (1.017 sec/step)
step 13028 	 loss = 1.063, (1.016 sec/step)
step 13029 	 loss = 1.014, (1.015 sec/step)
step 13030 	 loss = 1.143, (1.028 sec/step)
step 13031 	 loss = 1.566, (1.018 sec/step)
step 13032 	 loss = 0.855, (1.020 sec/step)
step 13033 	 loss = 0.726, (1.010 sec/step)
step 13034 	 loss = 0.679, (1.022 sec/step)
step 13035 	 loss = 0.971, (1.028 sec/step)
step 13036 	 loss = 0.927, (1.015 sec/step)
step 13037 	 loss = 0.746, (0.979 sec/step)
step 13038 	 loss = 0.855, (1.016 sec/step)
step 13039 	 loss = 1.229, (1.017 sec/step)
step 13040 	 loss = 0.663, (1.022 sec/step)
step 13041 	 loss = 0.732, (1.033 sec/step)
step 13042 	 loss = 0.616, (1.024 sec/step)
step 13043 	 loss = 0.403, (1.000 sec/step)
step 13044 	 loss = 0.722, (1.034 sec/step)
step 13045 	 loss = 0.934, (1.036 sec/step)
step 13046 	 loss = 1.050, (0.999 sec/step)
step 13047 	 loss = 0.526, (1.019 sec/step)
step 13048 	 loss = 1.003, (1.004 sec/step)
step 13049 	 loss = 0.731, (1.038 sec/step)
step 13050 	 loss = 0.514, (1.025 sec/step)
step 13051 	 loss = 0.648, (1.008 sec/step)
step 13052 	 loss = 0.459, (1.011 sec/step)
step 13053 	 loss = 0.744, (0.998 sec/step)
step 13054 	 loss = 0.537, (1.010 sec/step)
step 13055 	 loss = 0.530, (1.015 sec/step)
step 13056 	 loss = 0.639, (1.036 sec/step)
step 13057 	 loss = 0.548, (1.026 sec/step)
step 13058 	 loss = 0.625, (1.033 sec/step)
step 13059 	 loss = 0.787, (1.038 sec/step)
step 13060 	 loss = 1.275, (1.026 sec/step)
step 13061 	 loss = 2.233, (1.041 sec/step)
step 13062 	 loss = 0.789, (1.027 sec/step)
step 13063 	 loss = 1.135, (1.056 sec/step)
step 13064 	 loss = 0.694, (1.013 sec/step)
step 13065 	 loss = 1.017, (1.048 sec/step)
step 13066 	 loss = 0.735, (1.048 sec/step)
step 13067 	 loss = 1.004, (1.052 sec/step)
step 13068 	 loss = 0.796, (1.005 sec/step)
step 13069 	 loss = 0.654, (1.022 sec/step)
step 13070 	 loss = 0.955, (1.026 sec/step)
step 13071 	 loss = 0.649, (1.008 sec/step)
step 13072 	 loss = 0.515, (0.999 sec/step)
step 13073 	 loss = 0.790, (0.982 sec/step)
step 13074 	 loss = 0.592, (1.007 sec/step)
step 13075 	 loss = 0.553, (1.032 sec/step)
step 13076 	 loss = 0.845, (0.978 sec/step)
step 13077 	 loss = 0.494, (0.992 sec/step)
step 13078 	 loss = 0.764, (1.040 sec/step)
step 13079 	 loss = 1.111, (1.004 sec/step)
step 13080 	 loss = 0.687, (0.994 sec/step)
step 13081 	 loss = 0.656, (1.008 sec/step)
step 13082 	 loss = 0.797, (1.012 sec/step)
step 13083 	 loss = 1.225, (1.167 sec/step)
step 13084 	 loss = 0.904, (1.006 sec/step)
step 13085 	 loss = 1.018, (1.026 sec/step)
step 13086 	 loss = 1.385, (1.013 sec/step)
step 13087 	 loss = 2.502, (1.008 sec/step)
step 13088 	 loss = 1.844, (0.988 sec/step)
step 13089 	 loss = 1.521, (1.010 sec/step)
step 13090 	 loss = 0.939, (1.001 sec/step)
step 13091 	 loss = 1.580, (1.039 sec/step)
step 13092 	 loss = 1.286, (1.010 sec/step)
step 13093 	 loss = 1.766, (1.035 sec/step)
step 13094 	 loss = 1.466, (1.020 sec/step)
step 13095 	 loss = 1.768, (1.006 sec/step)
step 13096 	 loss = 1.765, (1.021 sec/step)
step 13097 	 loss = 1.363, (1.000 sec/step)
step 13098 	 loss = 1.294, (1.009 sec/step)
step 13099 	 loss = 1.414, (1.008 sec/step)
step 13100 	 loss = 1.146, (1.013 sec/step)
step 13101 	 loss = 1.032, (1.030 sec/step)
step 13102 	 loss = 0.765, (1.017 sec/step)
step 13103 	 loss = 0.838, (1.024 sec/step)
step 13104 	 loss = 0.712, (1.011 sec/step)
step 13105 	 loss = 1.022, (1.032 sec/step)
step 13106 	 loss = 1.330, (1.041 sec/step)
step 13107 	 loss = 1.530, (1.017 sec/step)
step 13108 	 loss = 1.014, (0.994 sec/step)
step 13109 	 loss = 0.936, (1.017 sec/step)
step 13110 	 loss = 1.616, (1.001 sec/step)
step 13111 	 loss = 1.535, (1.006 sec/step)
step 13112 	 loss = 3.276, (1.046 sec/step)
step 13113 	 loss = 2.440, (1.010 sec/step)
step 13114 	 loss = 1.541, (1.010 sec/step)
step 13115 	 loss = 1.519, (0.997 sec/step)
step 13116 	 loss = 1.740, (1.019 sec/step)
step 13117 	 loss = 1.382, (0.996 sec/step)
step 13118 	 loss = 1.969, (0.988 sec/step)
step 13119 	 loss = 2.276, (1.011 sec/step)
step 13120 	 loss = 1.035, (0.998 sec/step)
step 13121 	 loss = 1.278, (1.020 sec/step)
step 13122 	 loss = 1.538, (1.047 sec/step)
step 13123 	 loss = 1.091, (1.016 sec/step)
step 13124 	 loss = 2.880, (1.023 sec/step)
step 13125 	 loss = 1.555, (1.005 sec/step)
step 13126 	 loss = 2.391, (1.017 sec/step)
step 13127 	 loss = 3.157, (1.031 sec/step)
step 13128 	 loss = 1.849, (1.011 sec/step)
step 13129 	 loss = 2.180, (1.010 sec/step)
step 13130 	 loss = 1.177, (0.998 sec/step)
step 13131 	 loss = 1.368, (1.016 sec/step)
step 13132 	 loss = 1.061, (1.039 sec/step)
step 13133 	 loss = 1.285, (1.011 sec/step)
step 13134 	 loss = 0.802, (1.003 sec/step)
step 13135 	 loss = 1.865, (1.019 sec/step)
step 13136 	 loss = 3.044, (1.010 sec/step)
step 13137 	 loss = 1.468, (0.978 sec/step)
step 13138 	 loss = 1.520, (1.035 sec/step)
step 13139 	 loss = 1.646, (1.023 sec/step)
step 13140 	 loss = 1.616, (1.045 sec/step)
step 13141 	 loss = 1.202, (1.013 sec/step)
step 13142 	 loss = 1.713, (1.010 sec/step)
step 13143 	 loss = 1.374, (1.032 sec/step)
step 13144 	 loss = 1.278, (0.971 sec/step)
step 13145 	 loss = 0.779, (1.027 sec/step)
step 13146 	 loss = 1.333, (1.025 sec/step)
step 13147 	 loss = 1.133, (1.008 sec/step)
step 13148 	 loss = 1.116, (1.043 sec/step)
step 13149 	 loss = 1.057, (1.018 sec/step)
step 13150 	 loss = 0.776, (0.994 sec/step)
step 13151 	 loss = 1.182, (1.011 sec/step)
step 13152 	 loss = 0.958, (1.039 sec/step)
step 13153 	 loss = 1.059, (1.039 sec/step)
step 13154 	 loss = 0.972, (1.021 sec/step)
step 13155 	 loss = 1.366, (1.020 sec/step)
step 13156 	 loss = 0.865, (0.984 sec/step)
step 13157 	 loss = 0.955, (1.061 sec/step)
step 13158 	 loss = 1.279, (1.023 sec/step)
step 13159 	 loss = 1.133, (1.048 sec/step)
step 13160 	 loss = 0.638, (1.013 sec/step)
step 13161 	 loss = 0.897, (0.984 sec/step)
step 13162 	 loss = 0.933, (1.017 sec/step)
step 13163 	 loss = 0.749, (0.985 sec/step)
step 13164 	 loss = 0.539, (0.990 sec/step)
step 13165 	 loss = 0.655, (1.016 sec/step)
step 13166 	 loss = 0.525, (1.003 sec/step)
step 13167 	 loss = 1.675, (1.040 sec/step)
step 13168 	 loss = 0.852, (0.984 sec/step)
step 13169 	 loss = 0.830, (1.023 sec/step)
step 13170 	 loss = 0.547, (1.001 sec/step)
step 13171 	 loss = 0.681, (1.001 sec/step)
step 13172 	 loss = 0.882, (1.016 sec/step)
step 13173 	 loss = 0.574, (0.998 sec/step)
step 13174 	 loss = 1.012, (1.007 sec/step)
step 13175 	 loss = 0.861, (0.994 sec/step)
step 13176 	 loss = 0.941, (1.032 sec/step)
step 13177 	 loss = 1.422, (1.011 sec/step)
step 13178 	 loss = 1.978, (1.006 sec/step)
step 13179 	 loss = 3.914, (1.040 sec/step)
step 13180 	 loss = 9.576, (1.014 sec/step)
step 13181 	 loss = 15.447, (1.015 sec/step)
step 13182 	 loss = 8.376, (0.996 sec/step)
step 13183 	 loss = 5.555, (0.981 sec/step)
step 13184 	 loss = 1.375, (0.994 sec/step)
step 13185 	 loss = 1.688, (1.005 sec/step)
step 13186 	 loss = 1.330, (1.032 sec/step)
step 13187 	 loss = 1.706, (1.045 sec/step)
step 13188 	 loss = 1.914, (1.021 sec/step)
step 13189 	 loss = 3.592, (1.006 sec/step)
step 13190 	 loss = 2.320, (0.993 sec/step)
step 13191 	 loss = 2.337, (1.019 sec/step)
step 13192 	 loss = 2.135, (1.046 sec/step)
step 13193 	 loss = 1.657, (1.017 sec/step)
step 13194 	 loss = 1.997, (2.324 sec/step)
step 13195 	 loss = 2.140, (1.001 sec/step)
step 13196 	 loss = 2.200, (1.022 sec/step)
step 13197 	 loss = 1.794, (1.024 sec/step)
step 13198 	 loss = 1.908, (1.009 sec/step)
step 13199 	 loss = 1.711, (1.018 sec/step)
step 13200 	 loss = 1.537, (1.016 sec/step)
step 13201 	 loss = 1.631, (1.010 sec/step)
step 13202 	 loss = 1.679, (1.019 sec/step)
step 13203 	 loss = 1.808, (1.020 sec/step)
step 13204 	 loss = 1.541, (1.007 sec/step)
step 13205 	 loss = 1.940, (1.025 sec/step)
step 13206 	 loss = 1.521, (1.012 sec/step)
step 13207 	 loss = 1.243, (1.011 sec/step)
step 13208 	 loss = 1.374, (1.022 sec/step)
step 13209 	 loss = 1.655, (1.007 sec/step)
step 13210 	 loss = 1.763, (1.025 sec/step)
step 13211 	 loss = 1.502, (1.020 sec/step)
step 13212 	 loss = 1.761, (0.987 sec/step)
step 13213 	 loss = 1.573, (1.251 sec/step)
step 13214 	 loss = 1.534, (1.026 sec/step)
step 13215 	 loss = 1.603, (1.037 sec/step)
step 13216 	 loss = 1.903, (1.033 sec/step)
step 13217 	 loss = 1.820, (1.027 sec/step)
step 13218 	 loss = 1.442, (1.014 sec/step)
step 13219 	 loss = 1.513, (1.016 sec/step)
step 13220 	 loss = 1.599, (1.022 sec/step)
step 13221 	 loss = 1.525, (1.006 sec/step)
step 13222 	 loss = 1.415, (1.005 sec/step)
step 13223 	 loss = 1.315, (1.022 sec/step)
step 13224 	 loss = 1.492, (1.008 sec/step)
step 13225 	 loss = 1.326, (1.020 sec/step)
step 13226 	 loss = 1.394, (1.012 sec/step)
step 13227 	 loss = 1.680, (0.994 sec/step)
step 13228 	 loss = 1.129, (1.003 sec/step)
step 13229 	 loss = 1.099, (1.037 sec/step)
step 13230 	 loss = 1.243, (1.027 sec/step)
step 13231 	 loss = 1.426, (0.984 sec/step)
step 13232 	 loss = 1.656, (1.014 sec/step)
step 13233 	 loss = 1.091, (0.982 sec/step)
step 13234 	 loss = 0.926, (0.983 sec/step)
step 13235 	 loss = 1.138, (1.025 sec/step)
step 13236 	 loss = 1.641, (1.037 sec/step)
step 13237 	 loss = 1.415, (1.021 sec/step)
step 13238 	 loss = 1.440, (1.076 sec/step)
step 13239 	 loss = 1.241, (0.999 sec/step)
step 13240 	 loss = 1.356, (1.022 sec/step)
step 13241 	 loss = 1.057, (1.045 sec/step)
step 13242 	 loss = 1.206, (1.012 sec/step)
step 13243 	 loss = 1.025, (1.018 sec/step)
step 13244 	 loss = 1.249, (1.016 sec/step)
step 13245 	 loss = 1.138, (1.053 sec/step)
step 13246 	 loss = 1.092, (1.031 sec/step)
step 13247 	 loss = 0.927, (0.997 sec/step)
step 13248 	 loss = 1.429, (1.022 sec/step)
step 13249 	 loss = 1.254, (1.006 sec/step)
step 13250 	 loss = 2.023, (1.015 sec/step)
step 13251 	 loss = 1.603, (1.039 sec/step)
step 13252 	 loss = 0.664, (0.984 sec/step)
step 13253 	 loss = 1.034, (0.998 sec/step)
step 13254 	 loss = 0.898, (1.027 sec/step)
step 13255 	 loss = 1.186, (0.999 sec/step)
step 13256 	 loss = 1.195, (0.998 sec/step)
step 13257 	 loss = 1.113, (1.032 sec/step)
step 13258 	 loss = 1.350, (1.004 sec/step)
step 13259 	 loss = 1.146, (1.034 sec/step)
step 13260 	 loss = 1.059, (1.031 sec/step)
step 13261 	 loss = 1.437, (1.023 sec/step)
step 13262 	 loss = 0.758, (1.030 sec/step)
step 13263 	 loss = 1.284, (1.030 sec/step)
step 13264 	 loss = 0.822, (1.012 sec/step)
step 13265 	 loss = 1.206, (0.987 sec/step)
step 13266 	 loss = 0.967, (1.029 sec/step)
step 13267 	 loss = 0.856, (0.995 sec/step)
step 13268 	 loss = 1.121, (1.036 sec/step)
step 13269 	 loss = 0.806, (1.016 sec/step)
step 13270 	 loss = 0.827, (1.001 sec/step)
step 13271 	 loss = 0.805, (1.018 sec/step)
step 13272 	 loss = 0.970, (1.042 sec/step)
step 13273 	 loss = 0.928, (1.026 sec/step)
step 13274 	 loss = 1.548, (1.017 sec/step)
step 13275 	 loss = 0.656, (1.006 sec/step)
step 13276 	 loss = 0.972, (0.993 sec/step)
step 13277 	 loss = 0.972, (1.034 sec/step)
step 13278 	 loss = 1.033, (0.987 sec/step)
step 13279 	 loss = 1.359, (1.049 sec/step)
step 13280 	 loss = 0.763, (1.021 sec/step)
step 13281 	 loss = 0.900, (1.027 sec/step)
step 13282 	 loss = 1.177, (1.014 sec/step)
step 13283 	 loss = 0.590, (1.029 sec/step)
step 13284 	 loss = 1.116, (1.035 sec/step)
step 13285 	 loss = 0.886, (0.997 sec/step)
step 13286 	 loss = 0.883, (1.018 sec/step)
step 13287 	 loss = 0.865, (0.974 sec/step)
step 13288 	 loss = 1.021, (1.046 sec/step)
step 13289 	 loss = 1.020, (1.041 sec/step)
step 13290 	 loss = 0.951, (0.993 sec/step)
step 13291 	 loss = 1.119, (1.010 sec/step)
step 13292 	 loss = 0.934, (1.014 sec/step)
step 13293 	 loss = 0.805, (1.017 sec/step)
step 13294 	 loss = 1.141, (0.987 sec/step)
step 13295 	 loss = 1.020, (0.990 sec/step)
step 13296 	 loss = 0.619, (1.015 sec/step)
step 13297 	 loss = 0.969, (1.026 sec/step)
step 13298 	 loss = 0.920, (1.018 sec/step)
step 13299 	 loss = 0.947, (1.019 sec/step)
step 13300 	 loss = 0.902, (1.024 sec/step)
step 13301 	 loss = 0.489, (0.995 sec/step)
step 13302 	 loss = 1.246, (0.997 sec/step)
step 13303 	 loss = 1.029, (1.052 sec/step)
step 13304 	 loss = 0.826, (1.035 sec/step)
step 13305 	 loss = 1.025, (0.990 sec/step)
step 13306 	 loss = 0.898, (1.047 sec/step)
step 13307 	 loss = 1.341, (1.006 sec/step)
step 13308 	 loss = 1.166, (0.996 sec/step)
step 13309 	 loss = 1.081, (1.031 sec/step)
step 13310 	 loss = 0.855, (1.041 sec/step)
step 13311 	 loss = 0.796, (1.017 sec/step)
step 13312 	 loss = 0.597, (1.021 sec/step)
step 13313 	 loss = 0.675, (1.024 sec/step)
step 13314 	 loss = 0.967, (1.032 sec/step)
step 13315 	 loss = 1.159, (0.995 sec/step)
step 13316 	 loss = 0.953, (1.015 sec/step)
step 13317 	 loss = 0.963, (1.015 sec/step)

**Comment by DrSleep** [comment]
I haven't tested the training script - the given hyperparameters are just for demonstration.
