### ISSUE TITLE
model.ckpt-pretrained on val only gets Mean IoU: 0.059

### ISSUE THREAD

**Issue by yenlianglintw** [DrSleep/tensorflow-deeplab-lfov#9]
Is the model.ckpt-pretrained the final model for PASCAL 2012 ?  I used it for evaluate.py, but only got Mean IoU: 0.059 on val.txt

**Comment by Alice-Shen** [comment]
I did not use the ckpt file, but I ran the evaluate.py and got Mean IoU:0.001 on val.txt. Did you solve the problem?
